# Generated by Django 3.2.19 on 2026-04-15 10:08

import django.db  # type: ignore[reportMissingModuleSource]


class Migration(django.db.migrations.Migration):

    dependencies = [
        ('movies', '0002_add_genre_language_filtering'),
    ]

    operations = [
        django.db.migrations.RemoveIndex(
            model_name='genre',
            name='movies_genr_name_idx',
        ),
        django.db.migrations.RemoveIndex(
            model_name='language',
            name='movies_lang_code_idx',
        ),
        django.db.migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_name_idx',
        ),
        django.db.migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_rating_idx',
        ),
        django.db.migrations.RemoveIndex(
            model_name='movie',
            name='movies_movi_release_idx',
        ),
        django.db.migrations.AddIndex(
            model_name='genre',
            index=django.db.models.Index(fields=['name'], name='movies_genr_name_850734_idx'),
        ),
        django.db.migrations.AddIndex(
            model_name='language',
            index=django.db.models.Index(fields=['code'], name='movies_lang_code_56dee7_idx'),
        ),
        django.db.migrations.AddIndex(
            model_name='movie',
            index=django.db.models.Index(fields=['name'], name='movies_movi_name_98114c_idx'),
        ),
        django.db.migrations.AddIndex(
            model_name='movie',
            index=django.db.models.Index(fields=['rating'], name='movies_movi_rating_8fd49a_idx'),
        ),
        django.db.migrations.AddIndex(
            model_name='movie',
            index=django.db.models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx'),
        ),
    ]
