# Generated by Django 3.2.19 on 2026-04-15 13:12

from django.conf import settings 
from django.db import migrations, models 
import django.db.models.deletion
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0003_auto_20260415_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(editable=False, max_length=36, unique=True)),
                ('payment_id', models.CharField(editable=False, max_length=36, unique=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('total_tickets', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(default=timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_attempt_at', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booked_at']},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at'], name='movies_book_booked__a7ab7e_idx'),
        ),
        migrations.AddField(
            model_name='emailnotification',
            name='booking_batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_notification', to='movies.bookingbatch'),
        ),
        migrations.AddField(
            model_name='bookingbatch',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_batches', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='bookingbatch',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_batches', to='movies.theater'),
        ),
        migrations.AddField(
            model_name='bookingbatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.bookingbatch'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['status', 'next_attempt_at'], name='movies_emai_status_52c2dd_idx'),
        ),
        migrations.AddIndex(
            model_name='emailnotification',
            index=models.Index(fields=['created_at'], name='movies_emai_created_7ae2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingbatch',
            index=models.Index(fields=['booking_reference'], name='movies_book_booking_3713f3_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingbatch',
            index=models.Index(fields=['payment_id'], name='movies_book_payment_4bcfd0_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingbatch',
            index=models.Index(fields=['created_at'], name='movies_book_created_78326b_idx'),
        ),
    ]
