# Generated by Django 3.2.19 on 2026-04-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_trailer_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe')], default='stripe', max_length=16)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='initiated', max_length=16)),
                ('amount', models.PositiveIntegerField(help_text='Stored in the smallest currency unit.')),
                ('currency', models.CharField(default='inr', max_length=8)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('gateway_checkout_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('gateway_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('gateway_checkout_url', models.URLField(blank=True, null=True)),
                ('verification_reference', models.CharField(blank=True, max_length=255)),
                ('last_error', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bookingbatch',
            name='amount_total',
            field=models.PositiveIntegerField(default=0, help_text='Stored in the smallest currency unit.'),
        ),
        migrations.AddField(
            model_name='bookingbatch',
            name='currency',
            field=models.CharField(default='inr', max_length=8),
        ),
        migrations.AddField(
            model_name='bookingbatch',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingbatch',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingbatch',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_processing', 'Payment Processing'), ('confirmed', 'Confirmed'), ('payment_failed', 'Payment Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending_payment', max_length=32),
        ),
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='movies.bookingbatch')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_hold', to='movies.seat')),
            ],
            options={
                'ordering': ['seat__seat_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe', max_length=16)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=255)),
                ('signature_valid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='received', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='movies.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='booking_batch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transaction', to='movies.bookingbatch'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['expires_at'], name='movies_seat_expires_91758a_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentwebhookevent',
            index=models.Index(fields=['provider', 'event_type'], name='movies_paym_provide_cb8d34_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['status', 'created_at'], name='movies_paym_status_e8ceb3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['idempotency_key'], name='movies_paym_idempot_71c6c7_idx'),
        ),
    ]
