# Generated by Django 3.2.19 on 2026-04-15 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20260416_0102'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['movie', 'booked_at'], name='movies_book_movie_i_323598_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['theater', 'booked_at'], name='movies_book_theater_a2fd03_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingbatch',
            index=models.Index(fields=['status', 'finalized_at'], name='movies_book_status_288f24_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingbatch',
            index=models.Index(fields=['status', 'created_at'], name='movies_book_status_f69342_idx'),
        ),
    ]
