# Generated by Django 4.2.28 on 2026-05-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway_checkout_session_id',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway_payment_intent_id',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='verification_reference',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
