# Generated by Django 4.2.28 on 2026-05-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_paymenttransaction_gateway_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway_checkout_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
