# Generated by Django 4.2.28 on 2026-05-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_alter_paymenttransaction_gateway_checkout_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bookingbatch',
            index=models.Index(fields=['finalized_at'], name='movies_book_finaliz_2a99a2_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['theater', 'is_booked'], name='movies_seat_theater_7e5f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['theater', 'seat_number'], name='movies_seat_theater_2d8498_idx'),
        ),
        migrations.AddIndex(
            model_name='theater',
            index=models.Index(fields=['movie', 'time'], name='movies_thea_movie_i_352b0f_idx'),
        ),
    ]
